---
title: "HW 5"
author: "Clement Mugenzi"
date: "11/6/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(skimr)
library(purrr)
library(tidyr)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "right"))
```

# Problem 1

This is the code chunk that introduces missing data in the **iris** dataset.

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% view()
```

## Writing the Function

I will then create a function that will replace missing numeric values by the mean of that particular variable and also this function will replace missing character values with the the species **virginica**.


```{r}
missingness = function(x) {
  if (!is.numeric(x)) {
    replace(x, is.na(x), "virginica")
  } else if (is.numeric(x)) {
  replace(x, is.na(x), mean(x, na.rm = TRUE))
  }
}
```

```{r}
iris1 = 
  map_df(.x = iris_with_missing, ~ missingness(.x)) %>% 
  knitr::kable()
iris1
```













































































